### ISSUE TITLE
Task 'build' fails

### ISSUE THREAD

**Issue by elect86** [vihangpatil/kotlin-modules#1]
As titled

```
13:29:03: Executing task 'build'...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build
> Task :shape:compileKotlin
> Task :shape:compileJava NO-SOURCE
e: Module io.github.vihangpatil.kotlin.modules.shape cannot be found in the module graph
> Task :app:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
3 actionable tasks: 3 executed
13:29:06: Task execution finished 'build'.
´´´

**Comment by tombensve** [comment]
I get exactly the same problem when trying to use JPMS/Jigsaw with Groovy. The problem is that the 9+ java compiler expects all packages referenced in module-info.java to have those packages containing at least 1 java source file. It looks at the source tree when building, not already compiled classes.

In the case above the Shape class is written in kotlin. Java does not know about kotlin. When java compiles module-info.java it expects to see a Shape.java class since it is references in module-info.java. 

So for this to work there has to be support for a module-info.kt which is handled by the kotlin compiler.

**Comment by vihangpatil** [comment]
Sorry, for the delay.  I have managed to fix the build, but with limitations listed in README.  This build started to fail because of the incompatibility of the plugin used with later versions of `gradle` and `java`.  Will add this project to CI to know if the build starts to fail in future.
